# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_news.Categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateCreated',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.BooleanField(verbose_name='Опубликованно?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Заголовок новости'),
        ),
    ]
